#define DEF_SPRID_MOUSECURSOR				0

#define DEF_SPRID_INTERFACE_SPRFONTS		22
#define DEF_SPRID_INTERFACE_ADDINTERFACE	27
#define DEF_SPRID_INTERFACE_SPRFONTS2		28
#define DEF_SPRID_INTERFACE_F1HELPWINDOWS	29
#define DEF_SPRID_INTERFACE_FONT1			30	
#define DEF_SPRID_INTERFACE_FONT2			31
#define DEF_SPRID_INTERFACE_NEWMAPS1		35
#define DEF_SPRID_INTERFACE_NEWMAPS2		36
#define DEF_SPRID_INTERFACE_NEWMAPS3		37
#define DEF_SPRID_INTERFACE_NEWMAPS4		38
#define DEF_SPRID_INTERFACE_NEWMAPS5		39 

#define DEF_SPRID_INTERFACE_MONSTER			50
#define DEF_SPRID_INTERFACE_ND_LOADING		51
#define DEF_SPRID_INTERFACE_ND_MAINMENU		52
#define DEF_SPRID_INTERFACE_ND_LOGIN		53
#define DEF_SPRID_INTERFACE_ND_NEWACCOUNT	54
#define DEF_SPRID_INTERFACE_ND_QUIT			55
#define DEF_SPRID_INTERFACE_ND_AGREEMENT	56
#define DEF_SPRID_INTERFACE_ND_SELECTCHAR	57
#define DEF_SPRID_INTERFACE_ND_NEWCHAR		58
#define DEF_SPRID_INTERFACE_ND_NEWEXCHANGE	59
#define DEF_SPRID_INTERFACE_ND_GAME1		60
#define DEF_SPRID_INTERFACE_ND_GAME2		61
#define DEF_SPRID_INTERFACE_ND_GAME3		62
#define DEF_SPRID_INTERFACE_ND_GAME4		63
#define DEF_SPRID_INTERFACE_ND_ICONPANNEL	64
#define DEF_SPRID_INTERFACE_ND_INVENTORY	67
#define DEF_SPRID_INTERFACE_ND_TEXT			70
#define DEF_SPRID_INTERFACE_ND_BUTTON		71
#define DEF_SPRID_INTERFACE_ND_CRUSADE		72
#define DEF_SPRID_INTERFACE_GUIDEMAP		73

#define DEF_SPRID_INTERFACE_FEEDBACK1		40
#define DEF_SPRID_INTERFACE_FEEDBACK2		41
#define DEF_SPRID_INTERFACE_FEEDBACK3		42
#define DEF_SPRID_INTERFACE_FEEDBACK4		43
#define DEF_SPRID_INTERFACE_FEEDBACK5		44
#define DEF_SPRID_INTERFACE_FEEDBACK6		45
#define DEF_SPRID_INTERFACE_FEEDBACK7		46


//#define DEF_SPRID_BGTILE_PIVOTPOINT			200 //  <- 이 인덱스 번호는 결코 바뀔수 없다. 
//#define DEF_SPRID_EFFECT_PIVOTPOINT			20500 // 22000
#define DEF_SPRID_ITEMGROUND_PIVOTPOINT		100 //60
#define DEF_SPRID_ITEMEQUIP_PIVOTPOINT		200 //80
#define DEF_SPRID_ITEMPACK_PIVOTPOINT		300 //120
#define DEF_SPRID_ITEMDYNAMIC_PIVOTPOINT	400 //160
//#define DEF_SPRID_ITEMGROUND_PIVOTPOINT		20060 //60
//#define DEF_SPRID_ITEMEQUIP_PIVOTPOINT		20100 //80
//#define DEF_SPRID_ITEMPACK_PIVOTPOINT		20180 //120
//#define DEF_SPRID_ITEMDYNAMIC_PIVOTPOINT	20240 //160